#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/utils.sh"

function main() {
    unsupported "jackson" "2.7.0"
    unsupported "jackson" "2.7.1"
    unsupported "jackson" "2.7.2"
    unsupported "jackson" "2.7.3"
    unsupported "jackson" "2.7.4"
    unsupported "jackson" "2.7.5"
    unsupported "jackson" "2.7.6"
    unsupported "jackson" "2.7.7"
    unsupported "jackson" "2.7.8"
    unsupported "jackson" "2.7.9"
    unsupported "jackson" "2.8.0"
    unsupported "jackson" "2.8.1"
    unsupported "jackson" "2.8.10"
    unsupported "jackson" "2.8.11"
    unsupported "jackson" "2.8.2"
    unsupported "jackson" "2.8.3"
    unsupported "jackson" "2.8.4"
    unsupported "jackson" "2.8.5"
    unsupported "jackson" "2.8.6"
    unsupported "jackson" "2.8.7"
    unsupported "jackson" "2.8.8"
    unsupported "jackson" "2.8.9"
    check_lib_compatibility "jackson" "2.9.0" "$@"
    check_lib_compatibility "jackson" "2.9.1" "$@"
    check_lib_compatibility "jackson" "2.9.2" "$@"
    check_lib_compatibility "jackson" "2.9.3" "$@"
    check_lib_compatibility "jackson" "2.9.4" "$@"
    check_lib_compatibility "jackson" "2.9.5" "$@"
    check_lib_compatibility "jackson" "2.9.6" "$@"
    check_lib_compatibility "jackson" "2.9.7" "$@"
    check_lib_compatibility "jackson" "2.9.8" "$@"
    check_lib_compatibility "jackson" "2.9.9" "$@"
    check_lib_compatibility "jackson" "2.9.10" "$@"
    check_lib_compatibility "jackson" "2.10.0" "$@"
    check_lib_compatibility "jackson" "2.10.1" "$@"
    check_lib_compatibility "jackson" "2.10.2" "$@"
    check_lib_compatibility "jackson" "2.10.3" "$@"
    check_lib_compatibility "jackson" "2.10.4" "$@"
    check_lib_compatibility "jackson" "2.10.5" "$@"
    check_lib_compatibility "jackson" "2.11.0" "$@"
    check_lib_compatibility "jackson" "2.11.1" "$@"
    check_lib_compatibility "jackson" "2.11.2" "$@"
    check_lib_compatibility "jackson" "2.11.3" "$@"
    check_lib_compatibility "jackson" "2.11.4" "$@"
    check_lib_compatibility "jackson" "2.12.0" "$@"
    check_lib_compatibility "jackson" "2.12.1" "$@"
    check_lib_compatibility "jackson" "2.12.2" "$@"
    check_lib_compatibility "jackson" "2.12.3" "$@"
    check_lib_compatibility "jackson" "2.12.4" "$@"
    check_lib_compatibility "jackson" "2.12.5" "$@"
    check_lib_compatibility "jackson" "2.12.6" "$@"
    check_lib_compatibility "jackson" "2.12.7" "$@"
    check_lib_compatibility "jackson" "2.13.0" "$@"
    check_lib_compatibility "jackson" "2.13.1" "$@"
    check_lib_compatibility "jackson" "2.13.2" "$@"
    check_lib_compatibility "jackson" "2.13.3" "$@"
    check_lib_compatibility "jackson" "2.13.4" "$@"
    check_lib_compatibility "jackson" "2.13.5" "$@"
    check_lib_compatibility "jackson" "2.14.0" "$@"
    check_lib_compatibility "jackson" "2.14.1" "$@"
    check_lib_compatibility "jackson" "2.14.2" "$@"
    check_lib_compatibility "jackson" "2.14.3" "$@"
    check_lib_compatibility "jackson" "2.15.0" "$@"
    check_lib_compatibility "jackson" "2.15.1" "$@"
    check_lib_compatibility "jackson" "2.15.2" "$@"
    check_lib_compatibility "jackson" "2.15.3" "$@"
    check_lib_compatibility "jackson" "2.15.4" "$@"
    check_lib_compatibility "jackson" "2.16.0" "$@"
    check_lib_compatibility "jackson" "2.16.1" "$@"
    check_lib_compatibility "jackson" "2.16.2" "$@"
    check_lib_compatibility "jackson" "2.17.0" "$@"
    check_lib_compatibility "jackson" "2.17.1" "$@"
    check_lib_compatibility "jackson" "2.17.2" "$@"
    check_lib_compatibility "jackson" "2.17.3" "$@"
    check_lib_compatibility "jackson" "2.18.0" "$@"
    check_lib_compatibility "jackson" "2.18.1" "$@"
    check_lib_compatibility "jackson" "2.18.2" "$@"
    check_lib_compatibility "jackson" "2.18.3" "$@"
    check_lib_compatibility "jackson" "2.18.4" "$@"
    check_lib_compatibility "jackson" "2.18.5" "$@"
    check_lib_compatibility "jackson" "2.19.0" "$@"
    check_lib_compatibility "jackson" "2.19.1" "$@"
    check_lib_compatibility "jackson" "2.19.2" "$@"
    check_lib_compatibility "jackson" "2.19.3" "$@"
    check_lib_compatibility "jackson" "2.19.4" "$@"
    unsupported "jackson" "2.2.0"
    unsupported "jackson" "2.2.1"
    unsupported "jackson" "2.2.2"
    unsupported "jackson" "2.2.3"
    unsupported "jackson" "2.2.4"
    unsupported "jackson" "2.20.0"
    unsupported "jackson" "2.20.1"
    unsupported "jackson" "2.20.2"
    unsupported "jackson" "2.21.0"
}

main "$@"
